import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import Header from '../components/Header'
import Social from '../components/Social'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>kariston.dev | UI/UX Designer & Web developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <Social />
      <Hero />
    </>
  )
}
